import { DOC_TYPES } from '../../../ingestion/schemas.js';

export const DOCUMENT_FIELD_ALIASES = Object.freeze({
  [DOC_TYPES.INCOME_STATEMENT]: {
    revenue: ['revenue', 'net sales', 'total sales', 'sales'],
    cogs: ['cogs', 'cost of goods sold', 'cost of revenue', 'cost of sales'],
    grossProfit: ['gross profit', 'gross margin dollars'],
    operatingExpenses: ['operating expenses', 'opex', 'total operating expenses'],
    ebitda: ['ebitda', 'adjusted ebitda'],
    depreciation: ['depreciation', 'depreciation expense'],
    amortization: ['amortization', 'amortization expense'],
    interestExpense: ['interest expense', 'interest'],
    netIncome: ['net income', 'net earnings', 'profit after tax'],
    sga: ['sg&a', 'sga', 'selling general administrative', 'selling general and administrative'],
    __operatingProfit: ['operating profit', 'operating income', 'ebit'],
    __daCombined: ['d&a', 'depreciation & amortization', 'depreciation and amortization'],
  },
  [DOC_TYPES.BALANCE_SHEET]: {
    cash: ['cash', 'cash and equivalents', 'cash & equivalents'],
    accountsReceivable: ['accounts receivable', 'trade receivables', 'a/r'],
    inventory: ['inventory'],
    totalCurrentAssets: ['total current assets', 'current assets'],
    ppe: ['ppe', 'property plant and equipment', 'property, plant and equipment'],
    totalAssets: ['total assets'],
    accountsPayable: ['accounts payable', 'a/p', 'trade payables'],
    currentPortionLTD: ['current portion of ltd', 'current portion of long term debt', 'current maturities of debt'],
    totalCurrentLiabilities: ['total current liabilities', 'current liabilities'],
    longTermDebt: ['long term debt', 'long-term debt', 'lt debt'],
    totalLiabilities: ['total liabilities'],
    equity: ['equity', 'shareholders equity', 'stockholders equity', 'total equity'],
    goodwill: ['goodwill'],
    intangibles: ['intangibles', 'intangible assets'],
  },
  [DOC_TYPES.CASH_FLOW_STATEMENT]: {
    operatingCashFlow: ['operating cash flow', 'cash from operations', 'net cash provided by operating activities'],
    capex: ['capex', 'capital expenditures', 'capital expenditure'],
    investingCashFlow: ['investing cash flow', 'net cash used in investing activities'],
    financingCashFlow: ['financing cash flow', 'net cash from financing activities'],
    netChangeInCash: ['net change in cash', 'change in cash'],
    dividendsPaid: ['dividends paid', 'dividends'],
    debtRepayment: ['debt repayment', 'repayment of debt', 'debt paydown'],
  },
  [DOC_TYPES.AR_AGING]: {
    totalAR: ['total ar', 'accounts receivable', 'total receivables'],
    current: ['current', '0-30', '0 30', '0 to 30'],
    days30: ['31-60', '30-60', '1-30', '1 to 30'],
    days60: ['61-90', '60-90', '31-60 days', '31 to 60'],
    days90: ['91-120', '90-120', '61-90 days', '61 to 90'],
    days90Plus: ['120+', '90+', 'over 90', 'over 120', '120 plus', '90 plus'],
    concentrationTopCustomer: ['top customer %', 'top customer concentration'],
    concentrationTop5: ['top 5 %', 'top 5 concentration'],
  },
  [DOC_TYPES.AP_AGING]: {
    totalAP: ['total ap', 'accounts payable', 'total payables'],
    current: ['current', '0-30', '0 30', '0 to 30'],
    days30: ['31-60', '30-60', '1-30', '1 to 30'],
    days60: ['61-90', '60-90', '31-60 days', '31 to 60'],
    days90: ['91-120', '90-120', '61-90 days', '61 to 90'],
    days90Plus: ['120+', '90+', 'over 90', 'over 120', '120 plus', '90 plus'],
  },
  [DOC_TYPES.DEBT_SCHEDULE]: {
    totalDebt: ['total debt', 'outstanding debt'],
    annualDebtService: ['annual debt service', 'debt service'],
    weightedAvgRate: ['weighted average rate', 'weighted avg rate'],
    nearestMaturity: ['nearest maturity', 'next maturity'],
  },
  [DOC_TYPES.REVENUE_BREAKDOWN]: {
    totalRevenue: ['total revenue', 'total sales'],
    topCustomerPct: ['top customer %', 'top customer pct'],
    top3Pct: ['top 3 %', 'top 3 pct'],
    top5Pct: ['top 5 %', 'top 5 pct'],
    customerCount: ['customer count', 'number of customers'],
  },
  [DOC_TYPES.PROJECTIONS]: {
    projectedRevenue: ['projected revenue', 'forecast revenue', 'revenue'],
    projectedEbitda: ['projected ebitda', 'forecast ebitda', 'ebitda'],
    projectedGrowthRate: ['growth rate', 'projected growth rate', 'revenue growth'],
    projectedMargin: ['projected margin', 'ebitda margin', 'margin'],
  },
  [DOC_TYPES.TAX_RETURN]: {
    taxableIncome: ['taxable income'],
    totalTaxLiability: ['total tax liability', 'tax liability'],
    filingYear: ['filing year', 'tax year'],
    effectiveTaxRate: ['effective tax rate'],
    entityType: ['entity type'],
    grossReceipts: ['gross receipts', 'gross revenue'],
    officerCompensation: ['officer compensation'],
  },
  [DOC_TYPES.QOE_REPORT]: {
    adjustedEbitda: ['adjusted ebitda'],
    totalAddBacks: ['total add backs', 'total add-backs', 'total adjustments'],
    ownerCompensation: ['owner compensation', 'officer compensation'],
    normalizedOwnerComp: ['normalized owner comp', 'market owner compensation'],
    workingCapitalTarget: ['working capital target'],
    reportedEbitda: ['reported ebitda', 'ebitda'],
  },
});

export const COLUMN_ALIASES = Object.freeze({
  debtSchedule: {
    instrument: ['instrument', 'loan', 'facility', 'debt instrument'],
    principal: ['principal', 'balance', 'outstanding', 'amount'],
    interestRate: ['interest rate', 'rate', 'coupon'],
    maturityDate: ['maturity', 'maturity date'],
    annualDebtService: ['annual debt service', 'debt service'],
  },
  revenueConcentration: {
    name: ['customer', 'customer name', 'account', 'name'],
    revenue: ['revenue', 'sales', 'net sales'],
    percentage: ['percentage', '% of revenue', 'share', 'concentration'],
  },
});
